title: Ivy Design System 
email: dianameca@protonmail.com
url: "https://dianameca.ca/ivy-documentation"
twitter_username: jekyllrb
github_username:  jekyll
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme